### ISSUE TITLE
make a thing that shows you how to install it

### ISSUE THREAD

**Issue by notpoiu** [applesfruit/EZStats#1]
like this:

### Setting up

Make sure a java 8 jre is in your path

Clone the repository on your machine using

```
C:\Users\hello\Desktop>git clone https://github.com/applesfruit/EZStats
```

Then go into the directory

```
C:\Users\hello\Desktop>cd EZStats
```

and then run these commands command:
```
C:\Users\hello\Desktop\EzStats>.\gradlew
C:\Users\hello\Desktop\EzStats>.\gradlew setupDecompWorkspace
```

And then now it depends on you, if you want to use eclipse then type:
![Eclipse IDE](https://img.shields.io/badge/Eclipse-000000.svg?style=for-the-badge&logo=Eclipse-IDE&logoColor=white)
```
C:\Users\hello\Desktop\EzStats>.\gradlew eclipse
```

If you want to use IntelliJ then type this (also you need to install a plugin called Minecraft Developement):
![IntelliJ IDEA](https://img.shields.io/badge/IntelliJIDEA-000000.svg?style=for-the-badge&logo=intellij-idea&logoColor=white)
```
C:\Users\hello\Desktop\EzStats>.\gradlew genIntellijRuns
```

If you want to debug run this argument (--debug-jvm) :
## Without
```
C:\Users\hello\Desktop\EzStats>.\gradlew runClient
```
## With
```
C:\Users\hello\Desktop\EzStats>.\gradlew runClient --debug-jvm
```

**Comment by applesfruit** [comment]
That's for users that want to modify/fork this mod, however most end users will not want to do that and they can get the latest release here: https://github.com/applesfruit/EZStats/releases

**Comment by applesfruit** [comment]
It's just a forge mod that you drag into your "(MC DIRECTORY)\mods" folder, however for now make sure you are on a 1.7.10 Forge client.

**Comment by notpoiu** [comment]
i meant  like modifying the mod lol

**Comment by applesfruit** [comment]
mb lol
